Repository OlofSjogren/GoAyo, pull requests merged in 2020-10, with the labels that each got.

#81 Refactor ViewModels, adapters, and feature/pickuser-viewmodel
  .idea/navEditor.xml
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/main/java/com/goayo/debtify/view/AddDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/AddMembersFragment.java
  app/src/main/java/com/goayo/debtify/view/DetailedGroupActivity.java
  app/src/main/java/com/goayo/debtify/view/GroupFragment.java
  app/src/main/java/com/goayo/debtify/view/MyGroupsFragment.java
  app/src/main/java/com/goayo/debtify/view/PickUsersFragment.java
  app/src/main/java/com/goayo/debtify/view/SettleDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/ShowMembersFragment.java
  app/src/main/java/com/goayo/debtify/view/adapter/GroupViewAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/PickUserAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/TransactionCardAdapter.java
  app/src/main/java/com/goayo/debtify/viewModel/GroupsViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/AddDebtViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/DetailedGroupViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/GroupViewModelFactory.java
  app/src/main/java/com/goayo/debtify/viewmodel/MyGroupsViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/PickUserViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/SettleDebtViewModel.java
  app/src/main/res/layout/add_members_fragment.xml
  app/src/main/res/layout/group_fragment.xml
  app/src/main/res/layout/my_groups_cardview.xml
  app/src/main/res/layout/pick_user_cardview.xml
  app/src/main/res/layout/pick_users_fragment.xml
  app/src/main/res/layout/show_members_fragment.xml
  app/src/main/res/navigation/group_navigation_graph.xml
Labels: US05, US06, US08, refactor

#82 Sign in and register branch feature
  .idea/navEditor.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/goayo/debtify/IObservable.java
  app/src/main/java/com/goayo/debtify/IObserver.java
  app/src/main/java/com/goayo/debtify/model/Account.java
  app/src/main/java/com/goayo/debtify/model/IDatabase.java
  app/src/main/java/com/goayo/debtify/model/MockDatabase.java
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/main/java/com/goayo/debtify/view/LoginActivity.java
  app/src/main/java/com/goayo/debtify/view/MainActivity.java
  app/src/main/java/com/goayo/debtify/view/SignInFragment.java
  app/src/main/java/com/goayo/debtify/view/SignUpFragment.java
  app/src/main/java/com/goayo/debtify/viewmodel/SignInAndOutViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/SignUpViewModel.java
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/sign_in_fragment.xml
  app/src/main/res/layout/sign_up_fragment.xml
  app/src/main/res/menu/navdrawer_menu.xml
  app/src/main/res/navigation/login_navigation_graph.xml
  app/src/test/java/com/goayo/debtify/model/MockDatabaseTest.java
Labels: US02, US03

#91 Big decimal refactor
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules/app/app.plantuml
  app/src/main/java/com/goayo/debtify/model/Account.java
  app/src/main/java/com/goayo/debtify/model/Debt.java
  app/src/main/java/com/goayo/debtify/model/DebtTracker.java
  app/src/main/java/com/goayo/debtify/model/Group.java
  app/src/main/java/com/goayo/debtify/model/IDatabase.java
  app/src/main/java/com/goayo/debtify/model/Ledger.java
  app/src/main/java/com/goayo/debtify/model/MockDatabase.java
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/main/java/com/goayo/debtify/model/Payment.java
  app/src/main/java/com/goayo/debtify/modelaccess/IDebtData.java
  app/src/main/java/com/goayo/debtify/modelaccess/IGroupData.java
  app/src/main/java/com/goayo/debtify/modelaccess/IPaymentData.java
  app/src/main/java/com/goayo/debtify/view/AddDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/SettleDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/adapter/TransactionCardAdapter.java
  app/src/main/java/com/goayo/debtify/viewmodel/AddDebtViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/SettleDebtViewModel.java
  app/src/test/java/com/goayo/debtify/model/DebtTest.java
  app/src/test/java/com/goayo/debtify/model/DebtTrackerTest.java
  app/src/test/java/com/goayo/debtify/model/LedgerTest.java
  app/src/test/java/com/goayo/debtify/model/MockDatabaseTest.java
  app/src/test/java/com/goayo/debtify/model/PaymentTest.java
Labels: high priority

#92 Feature/group creation
  app/src/main/java/com/goayo/debtify/view/CreateGroupFragment.java
  app/src/main/java/com/goayo/debtify/view/GroupCreationActivity.java
  app/src/main/java/com/goayo/debtify/viewmodel/GroupCreationViewModel.java
  app/src/main/res/layout/create_group_fragment.xml
  app/src/main/res/navigation/group_creation_navigation_graph.xml
Labels: US04, task

#93 Patched appropriate classes in model to be package private
  app/src/main/java/com/goayo/debtify/model/Account.java
  app/src/main/java/com/goayo/debtify/model/IDatabase.java
Labels: high priority

#97 refactor/my-groups-cardview
  app/src/main/java/com/goayo/debtify/view/MyGroupsFragment.java
  app/src/main/java/com/goayo/debtify/view/adapter/GroupViewAdapter.java
  app/src/main/java/com/goayo/debtify/viewmodel/MyGroupsViewModel.java
Labels: enhancement, high priority

#98 feature/leave-group
  app/src/main/java/com/goayo/debtify/model/MockDatabase.java
  app/src/main/java/com/goayo/debtify/view/DetailedGroupActivity.java
  app/src/main/java/com/goayo/debtify/viewmodel/DetailedGroupViewModel.java
  app/src/main/res/menu/detailed_group_menu.xml
Labels: US19, enhancement

#100 refactor/pick-debt-cardview
  app/src/main/java/com/goayo/debtify/view/adapter/PickDebtAdapter.java
  app/src/main/res/layout/pick_debt_cardview.xml
Labels: enhancement, refactor

#106 fix the bug
  app/src/main/java/com/goayo/debtify/view/adapter/PickUserAdapter.java
Labels: bug

#102 bug/bypass-logout
  .idea/codeStyles/Project.xml
  app/src/main/java/com/goayo/debtify/view/MainActivity.java
Labels: bug

#107 Add/remove contacts feature
  .idea/navEditor.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/goayo/debtify/view/AddContactFragment.java
  app/src/main/java/com/goayo/debtify/view/ContactsActivity.java
  app/src/main/java/com/goayo/debtify/view/DisplayContactsFragment.java
  app/src/main/java/com/goayo/debtify/view/MainActivity.java
  app/src/main/java/com/goayo/debtify/view/PickUsersFragment.java
  app/src/main/java/com/goayo/debtify/view/adapter/ContactsViewAdapter.java
  app/src/main/java/com/goayo/debtify/viewmodel/AddContactViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/ContactsViewModel.java
  app/src/main/res/layout/activity_contacts.xml
  app/src/main/res/layout/add_contact_fragment.xml
  app/src/main/res/layout/display_contacts_fragment.xml
  app/src/main/res/menu/navdrawer_menu.xml
  app/src/main/res/navigation/contacts_navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: US10, enhancement

#115 Connect all event with viewmodels
  app/src/main/java/com/goayo/debtify/view/GroupFragment.java
  app/src/main/java/com/goayo/debtify/view/ShowMembersFragment.java
  app/src/main/java/com/goayo/debtify/view/adapter/ContactsViewAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/TransactionCardAdapter.java
  app/src/main/java/com/goayo/debtify/viewmodel/ContactsViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/DetailedGroupViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/GroupViewModelFactory.java
Labels: enhancement, refactor

#116 Fixed crash upon leaving group
  app/src/main/java/com/goayo/debtify/view/DetailedGroupActivity.java
  app/src/main/java/com/goayo/debtify/view/adapter/GroupViewAdapter.java
Labels: bug, high priority

#121 PickUserFragment destination refactor
  .idea/navEditor.xml
  app/src/main/java/com/goayo/debtify/view/CreateGroupFragment.java
  app/src/main/java/com/goayo/debtify/view/GroupCreationActivity.java
  app/src/main/java/com/goayo/debtify/view/PickUsersFragment.java
  app/src/main/java/com/goayo/debtify/viewmodel/PickUserViewModel.java
  app/src/main/res/navigation/group_creation_navigation_graph.xml
Labels: bug, enhancement, refactor

#118 Bug/display-surname-error
  app/src/main/java/com/goayo/debtify/model/MockDatabase.java
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/main/java/com/goayo/debtify/view/SignUpFragment.java
  app/src/main/java/com/goayo/debtify/view/adapter/PickDebtAdapter.java
Labels: bug

#108 Feature/split-debt-option
  .idea/codeStyles/Project.xml
  app/src/main/java/com/goayo/debtify/model/Account.java
  app/src/main/java/com/goayo/debtify/model/DebtSplitFactory.java
  app/src/main/java/com/goayo/debtify/model/EvenSplitStrategy.java
  app/src/main/java/com/goayo/debtify/model/Group.java
  app/src/main/java/com/goayo/debtify/model/IDatabase.java
  app/src/main/java/com/goayo/debtify/model/IDebtSplitStrategy.java
  app/src/main/java/com/goayo/debtify/model/Ledger.java
  app/src/main/java/com/goayo/debtify/model/MockDatabase.java
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/main/java/com/goayo/debtify/model/NoSplitStrategy.java
  app/src/main/java/com/goayo/debtify/view/AddDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/adapter/PickDebtAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/TransactionCardAdapter.java
  app/src/main/java/com/goayo/debtify/viewmodel/AddDebtViewModel.java
  app/src/main/res/layout/add_debt_fragment.xml
  app/src/main/res/layout/group_fragment.xml
Labels: enhancement, refactor

#126 Refactor/tabs
  .idea/navEditor.xml
  app/src/main/java/com/goayo/debtify/view/ActivityFragment.java
  app/src/main/java/com/goayo/debtify/view/HistoryFragment.java
  app/src/main/java/com/goayo/debtify/view/MainActivity.java
  app/src/main/java/com/goayo/debtify/view/factory/TabsFactory.java
  app/src/main/java/com/goayo/debtify/view/handler/TabsPagerAdapter.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/navigation/main_navigation_graph.xml
Labels: refactor

#124 fix a problem where empty selection will still cause the view to update
  app/src/main/java/com/goayo/debtify/view/AddDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/PickUsersFragment.java
Labels: bug

#127 Refactor/database injection branch
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/goayo/debtify/Database/DatabaseConnector.java
  app/src/main/java/com/goayo/debtify/Database/DbContactsFetcher.java
  app/src/main/java/com/goayo/debtify/Database/DbDebtsFetcher.java
  app/src/main/java/com/goayo/debtify/Database/DbGroupsFetcher.java
  app/src/main/java/com/goayo/debtify/Database/DbObject.java
  app/src/main/java/com/goayo/debtify/Database/DbPaymentFetcher.java
  app/src/main/java/com/goayo/debtify/Database/DbUserFetcher.java
  app/src/main/java/com/goayo/debtify/Database/RealDatabase.java
  app/src/main/java/com/goayo/debtify/Tuple.java
  app/src/main/java/com/goayo/debtify/model/Account.java
  app/src/main/java/com/goayo/debtify/model/DebtTracker.java
  app/src/main/java/com/goayo/debtify/model/EmptySelectionException.java
  app/src/main/java/com/goayo/debtify/model/EntityFactory.java
  app/src/main/java/com/goayo/debtify/model/EvenSplitStrategy.java
  app/src/main/java/com/goayo/debtify/model/FromJsonFactory.java
  app/src/main/java/com/goayo/debtify/model/Group.java
  app/src/main/java/com/goayo/debtify/model/IDatabase.java
  app/src/main/java/com/goayo/debtify/model/IDebtSplitStrategy.java
  app/src/main/java/com/goayo/debtify/model/Ledger.java
  app/src/main/java/com/goayo/debtify/model/MockDatabase.java
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/main/java/com/goayo/debtify/model/NoSplitStrategy.java
  app/src/main/java/com/goayo/debtify/model/UserNotLoggedInException.java
  app/src/main/java/com/goayo/debtify/view/LoginActivity.java
  app/src/main/java/com/goayo/debtify/viewmodel/SignUpViewModel.java
  app/src/test/java/com/goayo/debtify/model/AccountTest.java
  app/src/test/java/com/goayo/debtify/model/DebtTrackerTest.java
  app/src/test/java/com/goayo/debtify/model/LedgerTest.java
  app/src/test/java/com/goayo/debtify/model/MockDatabaseTest.java
  app/src/test/java/com/goayo/debtify/model/ModelEngineTest.java
  app/src/test/java/com/goayo/debtify/model/TestSuite.java
Labels: enhancement, refactor

#131 Added refresh functionality
  app/src/main/java/com/goayo/debtify/model/Account.java
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
Labels: enhancement

#133 fix problems with exceptions revolving add-debt functionality
  app/src/main/java/com/goayo/debtify/model/Account.java
  app/src/main/java/com/goayo/debtify/model/DebtException.java
  app/src/main/java/com/goayo/debtify/model/Group.java
  app/src/main/java/com/goayo/debtify/model/Ledger.java
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/main/java/com/goayo/debtify/viewmodel/AddContactViewModel.java
Labels: bug

#132 fix the issue where users can add themselves as a contact
  app/src/main/java/com/goayo/debtify/model/Account.java
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/main/java/com/goayo/debtify/view/AddContactFragment.java
  app/src/main/java/com/goayo/debtify/viewmodel/AddContactViewModel.java
Labels: bug

#134 Feature/swipe-refresh
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/java/com/goayo/debtify/model/Account.java
  app/src/main/java/com/goayo/debtify/view/GroupFragment.java
  app/src/main/java/com/goayo/debtify/view/MyGroupsFragment.java
  app/src/main/java/com/goayo/debtify/viewmodel/DetailedGroupViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/MyGroupsViewModel.java
  app/src/main/res/layout/group_fragment.xml
  app/src/main/res/layout/my_groups_fragment.xml
Labels: enhancement

#137 Set group name label in GroupFragment
  app/src/main/java/com/goayo/debtify/view/GroupFragment.java
Labels: enhancement

#140 Implementation/get single user from database
  .idea/codeStyles/Project.xml
  app/src/main/java/com/goayo/debtify/model/Account.java
  app/src/main/java/com/goayo/debtify/model/FromJsonFactory.java
  app/src/main/java/com/goayo/debtify/model/IDatabase.java
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/test/java/com/goayo/debtify/model/ModelEngineTest.java
Labels: enhancement

#138 Fix an issue where a lender can owe money to themselves
  app/src/main/java/com/goayo/debtify/model/Account.java
  app/src/main/java/com/goayo/debtify/model/Ledger.java
Labels: bug

#146 fixed tests
  app/src/test/java/com/goayo/debtify/model/ModelEngineTest.java
Labels: bug

#147 Changed EditText's maxline to 1
  .idea/codeStyles/Project.xml
  app/src/main/res/layout/create_group_fragment.xml
Labels: GUI, enhancement

#148 Refactored myGroupsFragment to RelativeLayouts, no more hardcoded values
  app/src/main/res/layout/my_groups_fragment.xml
Labels: refactor

#145 Contacts functionality bug fixes
  .idea/codeStyles/Project.xml
  app/src/main/java/com/goayo/debtify/model/Account.java
  app/src/main/java/com/goayo/debtify/view/AddContactFragment.java
  app/src/main/java/com/goayo/debtify/viewmodel/AddContactViewModel.java
  app/src/test/java/com/goayo/debtify/model/ModelEngineTest.java
Labels: bug

#144 Made SplitStrategies package private
  .idea/codeStyles/Project.xml
  app/src/main/java/com/goayo/debtify/model/EvenSplitStrategy.java
  app/src/main/java/com/goayo/debtify/model/NoSplitStrategy.java
Labels: refactor

#150 moved the intefaces into model and removed the folder
  .idea/codeStyles/Project.xml
  app/src/main/java/com/goayo/debtify/Database/DbDebtsFetcher.java
  app/src/main/java/com/goayo/debtify/Database/RealDatabase.java
  app/src/main/java/com/goayo/debtify/MockDatabase/MockDatabase.java
  app/src/main/java/com/goayo/debtify/model/Account.java
  app/src/main/java/com/goayo/debtify/model/DebtTracker.java
  app/src/main/java/com/goayo/debtify/model/EvenSplitStrategy.java
  app/src/main/java/com/goayo/debtify/model/Group.java
  app/src/main/java/com/goayo/debtify/model/IDatabase.java
  app/src/main/java/com/goayo/debtify/model/IDebtData.java
  app/src/main/java/com/goayo/debtify/model/IDebtSplitStrategy.java
  app/src/main/java/com/goayo/debtify/model/IGroupData.java
  app/src/main/java/com/goayo/debtify/model/IPaymentData.java
  app/src/main/java/com/goayo/debtify/model/IUserData.java
  app/src/main/java/com/goayo/debtify/model/Ledger.java
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/main/java/com/goayo/debtify/model/NoSplitStrategy.java
  app/src/main/java/com/goayo/debtify/model/Payment.java
  app/src/main/java/com/goayo/debtify/model/Tuple.java
  app/src/main/java/com/goayo/debtify/model/User.java
  app/src/main/java/com/goayo/debtify/view/AddContactFragment.java
  app/src/main/java/com/goayo/debtify/view/AddDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/CreateGroupFragment.java
  app/src/main/java/com/goayo/debtify/view/DisplayContactsFragment.java
  app/src/main/java/com/goayo/debtify/view/GroupFragment.java
  app/src/main/java/com/goayo/debtify/view/MyGroupsFragment.java
  app/src/main/java/com/goayo/debtify/view/PickUsersFragment.java
  app/src/main/java/com/goayo/debtify/view/SettleDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/ShowMembersFragment.java
  app/src/main/java/com/goayo/debtify/view/adapter/GroupViewAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/PickDebtAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/PickUserAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/TransactionCardAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/UserCardViewAdapter.java
  app/src/main/java/com/goayo/debtify/viewmodel/AddContactViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/AddDebtViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/ContactsViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/DetailedGroupViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/GroupCreationViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/MyGroupsViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/PickUserViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/SettleDebtViewModel.java
  app/src/test/java/com/goayo/debtify/model/AccountTest.java
  app/src/test/java/com/goayo/debtify/model/DebtTrackerTest.java
  app/src/test/java/com/goayo/debtify/model/GroupTest.java
  app/src/test/java/com/goayo/debtify/model/LedgerTest.java
  app/src/test/java/com/goayo/debtify/model/ModelEngineTest.java
Labels: refactor

#153 gui/detailed-group
  app/src/main/java/com/goayo/debtify/view/GroupFragment.java
  app/src/main/res/layout/group_fragment.xml
Labels: GUI, enhancement, refactor

#156 gui/settle-debt
  .idea/codeStyles/Project.xml
  app/src/main/res/layout/settle_debt_fragment.xml
  app/src/main/res/values/colors.xml
Labels: GUI, enhancement, refactor

#157 bug/recyclerview-on-focus
  app/src/main/java/com/goayo/debtify/view/GroupFragment.java
  app/src/main/java/com/goayo/debtify/view/MyGroupsFragment.java
Labels: GUI, bug

#159 Gui/group creation
  .idea/codeStyles/Project.xml
  app/src/main/res/layout/activity_group_creation.xml
  app/src/main/res/layout/create_group_fragment.xml
  app/src/main/res/layout/pick_users_fragment.xml
  app/src/main/res/layout/settle_debt_fragment.xml
  app/src/test/java/com/goayo/debtify/model/ModelEngineTest.java
Labels: GUI, enhancement, refactor

#158 Gui/add debt
  .idea/codeStyles/Project.xml
  app/src/main/res/layout/add_debt_fragment.xml
  app/src/main/res/layout/my_groups_fragment.xml
  app/src/main/res/layout/settle_debt_fragment.xml
Labels: GUI, enhancement, refactor

#163 Gui/debt cardview
  app/src/main/java/com/goayo/debtify/view/adapter/TransactionCardAdapter.java
  app/src/main/res/layout/detailed_group_transaction_cardview.xml
  app/src/main/res/layout/my_groups_cardview.xml
  app/src/main/res/layout/pick_debt_cardview.xml
  app/src/main/res/layout/pick_user_cardview.xml
  app/src/main/res/layout/user_cardview.xml
Labels: GUI

#168 Gui/contacts
  app/src/main/res/layout/add_contact_fragment.xml
  app/src/main/res/layout/display_contacts_fragment.xml
Labels: GUI

#166 Gui/drawerlayout
  app/src/main/java/com/goayo/debtify/view/MainActivity.java
  app/src/main/java/com/goayo/debtify/view/MyProfileFragment.java
  app/src/main/java/com/goayo/debtify/viewmodel/SignInAndOutViewModel.java
  app/src/main/res/drawable/whysplit.png
  app/src/main/res/layout/my_profile_fragment.xml
  app/src/main/res/layout/nav_header.xml
  app/src/main/res/menu/navdrawer_menu.xml
Labels: GUI

#169 Create documentation for the EntityFactory
  .idea/codeStyles/Project.xml
  app/src/main/java/com/goayo/debtify/model/EntityFactory.java
Labels: documentation

#165 add getUnfinishedDebts() method to filter the paid debts
  app/src/main/java/com/goayo/debtify/viewmodel/SettleDebtViewModel.java
Labels: bug

#154 Refactor ModelEngine's Singleton implementation
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/main/java/com/goayo/debtify/viewmodel/AddContactViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/AddDebtViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/ContactsViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/DetailedGroupViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/GroupCreationViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/ModelEngineViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/MyGroupsViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/PickUserViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/SettleDebtViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/SignInAndOutViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/SignUpViewModel.java
  app/src/test/java/com/goayo/debtify/model/ModelEngineTest.java
Labels: refactor

#176 Refactor/fix date database
  app/src/main/java/com/goayo/debtify/database/DbDebtsFetcher.java
  app/src/main/java/com/goayo/debtify/database/DbObject.java
  app/src/main/java/com/goayo/debtify/database/DbPaymentFetcher.java
  app/src/main/java/com/goayo/debtify/database/RealDatabase.java
  app/src/main/java/com/goayo/debtify/mockdatabase/MockDatabase.java
  app/src/main/java/com/goayo/debtify/mockdatabase/MockDbObject.java
  app/src/main/java/com/goayo/debtify/model/Account.java
  app/src/main/java/com/goayo/debtify/model/Debt.java
  app/src/main/java/com/goayo/debtify/model/DebtTracker.java
  app/src/main/java/com/goayo/debtify/model/FromJsonFactory.java
  app/src/main/java/com/goayo/debtify/model/Group.java
  app/src/main/java/com/goayo/debtify/model/IDatabase.java
  app/src/main/java/com/goayo/debtify/model/Ledger.java
  app/src/main/java/com/goayo/debtify/model/Payment.java
  app/src/test/java/com/goayo/debtify/model/DebtTest.java
  app/src/test/java/com/goayo/debtify/model/DebtTrackerTest.java
  app/src/test/java/com/goayo/debtify/model/LedgerTest.java
  app/src/test/java/com/goayo/debtify/model/ModelEngineTest.java
  app/src/test/java/com/goayo/debtify/model/PaymentTest.java
Labels: bug

#178 Improvements to enhance user experience
  .idea/codeStyles/Project.xml
  app/src/main/java/com/goayo/debtify/view/AddDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/MainActivity.java
  app/src/main/java/com/goayo/debtify/view/SettleDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/adapter/TransactionCardAdapter.java
  app/src/main/res/layout/add_contact_fragment.xml
  app/src/main/res/layout/create_group_fragment.xml
Labels: GUI

#181 Failed test since there were changes after the initial PR
  app/src/test/java/com/goayo/debtify/model/GroupTest.java
Labels: test

#182 Add Util class
  app/src/main/java/com/goayo/debtify/viewmodel/AddDebtViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/DetailedGroupViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/GroupCreationViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/ViewModelUtil.java
Labels: enhancement, refactor

#179 Updated JavaDoc for the ViewModel package
  app/src/main/java/com/goayo/debtify/view/GroupFragment.java
  app/src/main/java/com/goayo/debtify/viewmodel/AddContactViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/AddDebtViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/ContactsViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/DetailedGroupViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/GroupCreationViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/ModelEngineViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/MyGroupsViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/PickUserViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/SettleDebtViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/SignInAndOutViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/SignUpViewModel.java
Labels: documentation

#173 The displayed cards now sort after their given attribute
  .idea/codeStyles/Project.xml
  app/src/main/java/com/goayo/debtify/model/DebtTracker.java
  app/src/main/java/com/goayo/debtify/model/FromJsonFactory.java
  app/src/main/java/com/goayo/debtify/model/Group.java
  app/src/main/java/com/goayo/debtify/model/IDebtData.java
  app/src/main/java/com/goayo/debtify/model/IGroupData.java
  app/src/main/java/com/goayo/debtify/model/IPaymentData.java
  app/src/main/java/com/goayo/debtify/model/IUserData.java
  app/src/main/java/com/goayo/debtify/model/Payment.java
  app/src/main/java/com/goayo/debtify/model/User.java
  app/src/main/java/com/goayo/debtify/view/SettleDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/adapter/GroupViewAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/PickDebtAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/PickUserAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/TransactionCardAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/UserCardViewAdapter.java
  app/src/main/res/menu/navdrawer_menu.xml
  app/src/main/res/values/strings.xml
Labels: bug, enhancement

#183 Random values for Debt- and DebtTrackerTest
  app/src/test/java/com/goayo/debtify/model/DebtTest.java
  app/src/test/java/com/goayo/debtify/model/DebtTrackerTest.java
Labels: test

#186 Refactor/throw exceptions refactor
  .idea/codeStyles/Project.xml
  app/build.gradle
  app/src/main/java/com/goayo/debtify/database/RealDatabase.java
  app/src/main/java/com/goayo/debtify/mockdatabase/MockDatabase.java
  app/src/main/java/com/goayo/debtify/model/Account.java
  app/src/main/java/com/goayo/debtify/model/DebtException.java
  app/src/main/java/com/goayo/debtify/model/DebtTracker.java
  app/src/main/java/com/goayo/debtify/model/EventBus.java
  app/src/main/java/com/goayo/debtify/model/FromJsonFactory.java
  app/src/main/java/com/goayo/debtify/model/Group.java
  app/src/main/java/com/goayo/debtify/model/IDatabase.java
  app/src/main/java/com/goayo/debtify/model/Ledger.java
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/main/java/com/goayo/debtify/model/User.java
  app/src/main/java/com/goayo/debtify/viewmodel/AddDebtViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/ContactsViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/DetailedGroupViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/MyGroupsViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/SettleDebtViewModel.java
  app/src/test/java/com/goayo/debtify/model/DebtTest.java
  app/src/test/java/com/goayo/debtify/model/DebtTrackerTest.java
  app/src/test/java/com/goayo/debtify/model/GroupTest.java
  app/src/test/java/com/goayo/debtify/model/LedgerTest.java
Labels: refactor

#188 Fixed remaining todos, mostly regarding specification of thrown
  app/src/main/java/com/goayo/debtify/view/AddDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/DebtActivity.java
  app/src/main/java/com/goayo/debtify/view/GroupFragment.java
  app/src/main/java/com/goayo/debtify/view/MyGroupsFragment.java
  app/src/main/java/com/goayo/debtify/view/SettleDebtFragment.java
  app/src/main/java/com/goayo/debtify/viewmodel/AddDebtViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/ContactsViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/DetailedGroupViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/GroupCreationViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/MyGroupsViewModel.java
  app/src/main/res/values/strings.xml
Labels: refactor

#191 gui/minor-tweaks
  app/src/main/java/com/goayo/debtify/view/SettleDebtFragment.java
  app/src/main/res/layout/pick_debt_cardview.xml
Labels: GUI

#192 Added animation to login & registration pages.
  app/src/main/java/com/goayo/debtify/view/SignInFragment.java
  app/src/main/java/com/goayo/debtify/view/SignUpFragment.java
  app/src/main/res/drawable/gradient_1.xml
  app/src/main/res/drawable/gradient_2.xml
  app/src/main/res/drawable/gradient_3.xml
  app/src/main/res/drawable/gradient_list.xml
  app/src/main/res/layout/sign_in_fragment.xml
  app/src/main/res/layout/sign_up_fragment.xml
Labels: GUI

#184 test/modelengine
  app/src/test/java/com/goayo/debtify/model/ModelEngineTest.java
Labels: test

#196 Organized view package into subfolders
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/goayo/debtify/view/MainActivity.java
  app/src/main/java/com/goayo/debtify/view/contact/AddContactFragment.java
  app/src/main/java/com/goayo/debtify/view/contact/ContactsActivity.java
  app/src/main/java/com/goayo/debtify/view/contact/DisplayContactsFragment.java
  app/src/main/java/com/goayo/debtify/view/debt/AddDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/debt/DebtActivity.java
  app/src/main/java/com/goayo/debtify/view/debt/SettleDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/group/CreateGroupFragment.java
  app/src/main/java/com/goayo/debtify/view/group/DetailedGroupActivity.java
  app/src/main/java/com/goayo/debtify/view/group/GroupCreationActivity.java
  app/src/main/java/com/goayo/debtify/view/group/GroupFragment.java
  app/src/main/java/com/goayo/debtify/view/group/MyGroupsFragment.java
  app/src/main/java/com/goayo/debtify/view/group/ShowMembersFragment.java
  app/src/main/java/com/goayo/debtify/view/login/LoginActivity.java
  app/src/main/java/com/goayo/debtify/view/login/SignInFragment.java
  app/src/main/java/com/goayo/debtify/view/login/SignUpFragment.java
  app/src/main/java/com/goayo/debtify/view/util/PickUsersFragment.java
  app/src/main/res/layout/activity_contacts.xml
  app/src/main/res/layout/activity_debt.xml
  app/src/main/res/layout/activity_detailed_group.xml
  app/src/main/res/layout/activity_group_creation.xml
  app/src/main/res/layout/add_contact_fragment.xml
  app/src/main/res/navigation/add_debt_navigation_graph.xml
  app/src/main/res/navigation/contacts_navigation_graph.xml
  app/src/main/res/navigation/group_creation_navigation_graph.xml
  app/src/main/res/navigation/group_navigation_graph.xml
  app/src/main/res/navigation/login_navigation_graph.xml
  app/src/main/res/navigation/main_navigation_graph.xml
  app/src/main/res/navigation/settle_debt_navigation_graph.xml
Labels: refactor

#204 Tests/coverage sweep
  app/src/androidTest/java/com/goayo/debtify/ExampleInstrumentedTest.java
  app/src/main/java/com/goayo/debtify/database/RealDatabase.java
  app/src/main/java/com/goayo/debtify/mockdatabase/MockDatabase.java
  app/src/main/java/com/goayo/debtify/model/EmptySelectionException.java
  app/src/main/java/com/goayo/debtify/model/EvenSplitStrategy.java
  app/src/main/java/com/goayo/debtify/model/FromJsonFactory.java
  app/src/main/java/com/goayo/debtify/model/IDatabase.java
  app/src/main/java/com/goayo/debtify/model/InvalidDebtException.java
  app/src/main/java/com/goayo/debtify/model/JsonString.java
  app/src/main/java/com/goayo/debtify/model/Ledger.java
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/main/java/com/goayo/debtify/model/Session.java
  app/src/main/java/com/goayo/debtify/viewmodel/SettleDebtViewModel.java
  app/src/test/java/com/goayo/debtify/model/DebtTrackerTest.java
  app/src/test/java/com/goayo/debtify/model/GroupTest.java
  app/src/test/java/com/goayo/debtify/model/LedgerTest.java
  app/src/test/java/com/goayo/debtify/model/ModelEngineTest.java
  app/src/test/java/com/goayo/debtify/model/UserTest.java
Labels: enhancement

#205 Add eventbus tests
  app/src/test/java/com/goayo/debtify/model/EventBusTest.java
  app/src/test/java/com/goayo/debtify/model/ModelEngineTest.java
  app/src/test/java/com/goayo/debtify/model/TestSuite.java
Labels: enhancement

#206 Removed dependency on viewmodel from mockdtabase
  app/src/main/java/com/goayo/debtify/mockdatabase/MockDatabase.java
Labels: refactor

#202 Documentation/fix capitalization of author
  Documents/JavaDocs/javadocs.zip
  Documents/STAN/analys/.stan
  Documents/STAN/stan_model_analysis.svg
  app/src/main/java/com/goayo/debtify/mockdatabase/MockDatabase.java
  app/src/main/java/com/goayo/debtify/model/EntityFactory.java
  app/src/main/java/com/goayo/debtify/model/EventBus.java
  app/src/main/java/com/goayo/debtify/model/FromJsonFactory.java
  app/src/main/java/com/goayo/debtify/model/IDatabase.java
  app/src/main/java/com/goayo/debtify/model/IEventHandler.java
  app/src/main/java/com/goayo/debtify/model/JsonString.java
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/main/java/com/goayo/debtify/viewmodel/SignInAndOutViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/SignUpViewModel.java
  app/src/test/java/com/goayo/debtify/model/ModelEngineTest.java
Labels: documentation

#203 Reformat the whole codebase to have consistent code styles
  app/src/main/java/com/goayo/debtify/model/DebtTracker.java
  app/src/main/java/com/goayo/debtify/model/EntityFactory.java
  app/src/main/java/com/goayo/debtify/model/EventBus.java
  app/src/main/java/com/goayo/debtify/model/Group.java
  app/src/main/java/com/goayo/debtify/model/GroupNotFoundException.java
  app/src/main/java/com/goayo/debtify/model/IDatabase.java
  app/src/main/java/com/goayo/debtify/model/InvalidPaymentException.java
  app/src/main/java/com/goayo/debtify/model/Ledger.java
  app/src/main/java/com/goayo/debtify/model/LoginException.java
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/main/java/com/goayo/debtify/model/Payment.java
  app/src/main/java/com/goayo/debtify/model/RegistrationException.java
  app/src/main/java/com/goayo/debtify/model/Session.java
  app/src/main/java/com/goayo/debtify/model/Tuple.java
  app/src/main/java/com/goayo/debtify/model/User.java
  app/src/main/java/com/goayo/debtify/model/UserAlreadyExistsException.java
  app/src/main/java/com/goayo/debtify/model/UserNotFoundException.java
  app/src/main/java/com/goayo/debtify/model/UserNotLoggedInException.java
  app/src/main/java/com/goayo/debtify/view/adapter/GroupViewAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/PickDebtAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/PickUserAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/TransactionCardAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/UserCardViewAdapter.java
  app/src/main/java/com/goayo/debtify/view/contact/AddContactFragment.java
  app/src/main/java/com/goayo/debtify/view/contact/DisplayContactsFragment.java
  app/src/main/java/com/goayo/debtify/view/debt/AddDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/debt/DebtActivity.java
  app/src/main/java/com/goayo/debtify/view/debt/SettleDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/group/CreateGroupFragment.java
  app/src/main/java/com/goayo/debtify/view/group/DetailedGroupActivity.java
  app/src/main/java/com/goayo/debtify/view/group/GroupCreationActivity.java
  app/src/main/java/com/goayo/debtify/view/group/GroupFragment.java
  app/src/main/java/com/goayo/debtify/view/group/MyGroupsFragment.java
  app/src/main/java/com/goayo/debtify/view/group/ShowMembersFragment.java
  app/src/main/java/com/goayo/debtify/view/login/LoginActivity.java
  app/src/main/java/com/goayo/debtify/view/login/SignInFragment.java
  app/src/main/java/com/goayo/debtify/view/login/SignUpFragment.java
  app/src/main/java/com/goayo/debtify/view/util/PickUsersFragment.java
  app/src/main/java/com/goayo/debtify/viewmodel/GroupCreationViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/ModelEngineViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/MyGroupsViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/SignInAndOutViewModel.java
  app/src/main/java/com/goayo/debtify/viewmodel/ViewModelUtil.java
Labels: documentation, refactor

#207 Made small changes to make the real database work with hashedpassword…
  app/src/main/java/com/goayo/debtify/database/DbUserFetcher.java
  app/src/main/java/com/goayo/debtify/database/RealDatabase.java
  app/src/main/java/com/goayo/debtify/viewmodel/ModelEngineViewModel.java
Labels: bug

#208 Merged the server software in with the repo
  ServerSoftware/.idea/codeStyles/codeStyleConfig.xml
  ServerSoftware/.idea/jsLibraryMappings.xml
  ServerSoftware/.idea/modules.xml
  ServerSoftware/.idea/vcs.xml
  ServerSoftware/.idea/workspace.xml
  ServerSoftware/Server/Server.js
  ServerSoftware/Server/database.json
  ServerSoftware/Server/gettingInfo
  ServerSoftware/Server/routes/debts.js
  ServerSoftware/Server/routes/groups.js
  ServerSoftware/Server/routes/login.js
  ServerSoftware/Server/routes/payments.js
  ServerSoftware/Server/routes/users.js
  ServerSoftware/package-lock.json
  ServerSoftware/package.json
Labels: enhancement
