Repository OlofSjogren/GoAyo, pull requests merged in 2020-09, with the labels that each got.

#30 User class
  app/src/androidTest/java/com/goayo/debtify/model/UserTest.java
  app/src/main/java/com/goayo/debtify/model/User.java
Labels: enhancement

#34 First draft of the mock database
  app/src/main/java/com/goayo/debtify/model/database/IDatabase.java
  app/src/main/java/com/goayo/debtify/model/database/MockDatabase.java
Labels: enhancement

#35 Debt feature branch
  app/src/main/java/com/goayo/debtify/model/Debt.java
  app/src/main/java/com/goayo/debtify/model/DebtTracker.java
  app/src/main/java/com/goayo/debtify/model/Group.java
  app/src/main/java/com/goayo/debtify/model/Ledger.java
  app/src/main/java/com/goayo/debtify/model/Payment.java
  app/src/main/java/com/goayo/debtify/model/User.java
  app/src/main/java/com/goayo/debtify/modelaccess/IDebtData.java
  app/src/main/java/com/goayo/debtify/modelaccess/IGroupData.java
  app/src/main/java/com/goayo/debtify/modelaccess/IPaymentData.java
  app/src/test/java/com/goayo/debtify/model/debt/DebtTest.java
  app/src/test/java/com/goayo/debtify/model/debt/DebtTrackerTest.java
  app/src/test/java/com/goayo/debtify/model/debt/LedgerTest.java
  app/src/test/java/com/goayo/debtify/model/debt/PaymentTest.java
Labels: enhancement

#31 Model facade feature
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
Labels: enhancement

#38 move database files up one hiachy, and remove the database-package
  app/src/main/java/com/goayo/debtify/model/IDatabase.java
  app/src/main/java/com/goayo/debtify/model/MockDatabase.java
Labels: bug

#39 move testfiles from debt.model to model
  app/src/test/java/com/goayo/debtify/model/DebtTest.java
  app/src/test/java/com/goayo/debtify/model/DebtTrackerTest.java
  app/src/test/java/com/goayo/debtify/model/LedgerTest.java
  app/src/test/java/com/goayo/debtify/model/PaymentTest.java
Labels: bug

#45 Gui group feature branch
  .idea/codeStyles/Project.xml
  .idea/navEditor.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/goayo/debtify/view/CreateGroupFragment.java
  app/src/main/java/com/goayo/debtify/view/GroupCreationActivity.java
  app/src/main/java/com/goayo/debtify/view/MainActivity.java
  app/src/main/java/com/goayo/debtify/view/MyGroupsFragment.java
  app/src/main/java/com/goayo/debtify/view/PickUsersFragment.java
  app/src/main/java/com/goayo/debtify/view/adapter/GroupViewAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/PickUserAdapter.java
  app/src/main/res/drawable/ic_baseline_add_24.xml
  app/src/main/res/layout/activity_group_creation.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/create_group_fragment.xml
  app/src/main/res/layout/group_fragment.xml
  app/src/main/res/layout/my_groups_cardview.xml
  app/src/main/res/layout/my_groups_fragment.xml
  app/src/main/res/layout/pick_user_cardview.xml
  app/src/main/res/layout/pick_users_fragment.xml
  app/src/main/res/navigation/group_creation_navigation_graph.xml
  app/src/main/res/values/strings.xml
Labels: US04

#51 Gui detailed group view
  .idea/navEditor.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/goayo/debtify/view/AddMembersFragment.java
  app/src/main/java/com/goayo/debtify/view/DetailedGroupActivity.java
  app/src/main/java/com/goayo/debtify/view/GroupFragment.java
  app/src/main/java/com/goayo/debtify/view/ShowMembersFragment.java
  app/src/main/java/com/goayo/debtify/view/adapter/TransactionCardAdapter.java
  app/src/main/res/layout/activity_detailed_group.xml
  app/src/main/res/layout/add_members_fragment.xml
  app/src/main/res/layout/detailed_group_transaction_cardview.xml
  app/src/main/res/layout/group_fragment.xml
  app/src/main/res/layout/show_members_fragment.xml
  app/src/main/res/menu/detailed_group_menu.xml
  app/src/main/res/navigation/group_navigation_graph.xml
  app/src/main/res/values/colors.xml
Labels: US04, US05

#52 Couple of view implementations
  .idea/navEditor.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/goayo/debtify/view/AddDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/AddExpenseFragment.java
  app/src/main/java/com/goayo/debtify/view/DebtActivity.java
  app/src/main/java/com/goayo/debtify/view/GroupFragment.java
  app/src/main/java/com/goayo/debtify/view/SettleDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/SettleUpFragment.java
  app/src/main/java/com/goayo/debtify/view/adapter/PickDebtAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/UserCardViewAdapter.java
  app/src/main/res/layout/activity_debt.xml
  app/src/main/res/layout/add_debt_fragment.xml
  app/src/main/res/layout/add_expense_fragment.xml
  app/src/main/res/layout/pick_debt_cardview.xml
  app/src/main/res/layout/settle_debt_fragment.xml
  app/src/main/res/layout/settle_up_fragment.xml
  app/src/main/res/layout/user_cardview.xml
  app/src/main/res/navigation/add_debt_navigation_graph.xml
  app/src/main/res/navigation/main_navigation_graph.xml
  app/src/main/res/navigation/settle_debt_navigation_graph.xml
Labels: US06, US08, enhancement

#56 fix the error
  Documents/Meetings/M12-25-09.pdf
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/goayo/debtify/view/DetailedGroupActivity.java
  app/src/main/res/values/styles.xml
Labels: bug, high priority

#75 Group view model test
  .idea/codeStyles/Project.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/main/java/com/goayo/debtify/view/DetailedGroupActivity.java
  app/src/main/java/com/goayo/debtify/view/GroupFragment.java
  app/src/main/java/com/goayo/debtify/view/MyGroupsFragment.java
  app/src/main/java/com/goayo/debtify/view/adapter/GroupViewAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/TransactionCardAdapter.java
  app/src/main/java/com/goayo/debtify/viewModel/GroupViewModelFactory.java
  app/src/main/java/com/goayo/debtify/viewModel/GroupsViewModel.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/detailed_group_transaction_cardview.xml
  app/src/main/res/layout/group_fragment.xml
  app/src/main/res/layout/my_groups_cardview.xml
  app/src/main/res/layout/my_groups_fragment.xml
  app/src/main/res/menu/detailed_group_menu.xml
  app/src/main/res/navigation/main_navigation_graph.xml
  app/src/main/res/values/styles.xml
Labels: US05

#76 Header comments for the concerned xml files
  app/src/main/res/layout/activity_debt.xml
  app/src/main/res/layout/activity_detailed_group.xml
  app/src/main/res/layout/activity_fragment.xml
  app/src/main/res/layout/activity_group_creation.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/add_debt_fragment.xml
  app/src/main/res/layout/create_group_fragment.xml
  app/src/main/res/layout/detailed_group_transaction_cardview.xml
  app/src/main/res/layout/group_fragment.xml
  app/src/main/res/layout/my_groups_cardview.xml
  app/src/main/res/layout/my_groups_fragment.xml
  app/src/main/res/layout/nav_header.xml
  app/src/main/res/layout/pick_debt_cardview.xml
  app/src/main/res/layout/pick_user_cardview.xml
  app/src/main/res/layout/pick_users_fragment.xml
  app/src/main/res/layout/settle_debt_fragment.xml
  app/src/main/res/layout/show_members_fragment.xml
  app/src/main/res/layout/sign_in_fragment.xml
  app/src/main/res/layout/sign_up_fragment.xml
  app/src/main/res/layout/user_cardview.xml
Labels: documentation

#74 add debt description
  .idea/codeStyles/Project.xml
  app/src/main/java/com/goayo/debtify/model/Account.java
  app/src/main/java/com/goayo/debtify/model/DebtTracker.java
  app/src/main/java/com/goayo/debtify/model/Group.java
  app/src/main/java/com/goayo/debtify/model/Ledger.java
  app/src/main/java/com/goayo/debtify/model/ModelEngine.java
  app/src/main/java/com/goayo/debtify/modelaccess/IDebtData.java
  app/src/main/java/com/goayo/debtify/view/DebtActivity.java
  app/src/main/java/com/goayo/debtify/view/adapter/PickDebtAdapter.java
  app/src/main/java/com/goayo/debtify/view/adapter/TransactionCardAdapter.java
  app/src/main/res/layout/add_debt_fragment.xml
  app/src/main/res/layout/pick_debt_cardview.xml
  app/src/test/java/com/goayo/debtify/model/DebtTrackerTest.java
  app/src/test/java/com/goayo/debtify/model/LedgerTest.java
Labels: US06, US08, high priority, refactor

#80 The remaining functionalities of DebtActivity
  app/src/main/java/com/goayo/debtify/view/AddDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/SettleDebtFragment.java
  app/src/main/java/com/goayo/debtify/view/adapter/UserCardViewAdapter.java
  app/src/main/java/com/goayo/debtify/viewModel/AddDebtViewModel.java
  app/src/main/java/com/goayo/debtify/viewModel/SettleDebtViewModel.java
  app/src/main/res/layout/settle_debt_fragment.xml
Labels: US06, US08, enhancement
